### ISSUE TITLE
Add flags and metadata

### ISSUE THREAD

**Issue by jlperla** [JuliaDiffEq/SciCompDSL.jl#21]
Right now you have a single `subtype::Symbol` to differentiate types of variables.  Since it is a `Symbol` it seems very generic, but it also means you can only categorise by one type.

I would like to be able to put in multiple levels of categorization given information known at compile-time.  Could either the `subtype` be extended to support a named tuple of symbols, or could there be an additional `flags` which allows a set of `Symbol` flags (also preferably as a named tuple).

**Comment by ChrisRackauckas** [comment]
>I would like to be able to put in multiple levels of categorization given information known at compile-time. Could either the subtype be extended to support a named tuple of symbols, or could there be an additional flags which allows a set of Symbol flags (also preferably as a named tuple).

No, why do you want so much compile-time information in there? That would be very bad for performance. We want to leave `subtype` strictly typed since it'll be touched in many different ways so it needs to be performant. However, adding an untyped `flag` field for some extra pieces might be useful (which are distinct from `value`). It just hasn't been added since it hasn't been needed yet. Feel free to add it in a PR where you need it for some functionality.

**Comment by jlperla** [comment]
The question is whether you are trying to put in enough flexibility to allow people to experiment with the library without modifying it (and potentially breaking other users).  I understand your approach to leave all features until you need them... it is a consistent approach as long as you know how you would design it later.

I am not about to go and design a DSGE model anytime soon, but if the interface doesn't support having a 2nd level of categorization (where totally different code would be generated based on it) then it wouldn't work for that application.  The classic example is the categorization of variables into predetermined or not.  You organize matrices in very different ways, check different eigenvalues, etc.  If you are curious, you can see this in http://www.wouterdenhaan.com/numerical/BKconditionsslides.pdf  

For my immediate needs in solving continuous time methods, I am not sure I need it.

Whether that needs to be available at compile-time is a design question for you.  I come from a C++ TMP mindset where you almost always want type-safe compile-time information if possible in order to generate specialized algorithms, but maybe that is the wrong approach in Julia.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/SciCompDSL.jl/commit/647ba72bee1182383726ba6da1cc4ba3ed79ab7c
