### ISSUE TITLE
Add Brownian motion or differential white noise variable

### ISSUE THREAD

**Issue by mschauer** [JuliaDiffEq/SciCompDSL.jl#24]
I suppose this is planned all along. ;-)

**Comment by ChrisRackauckas** [comment]
Yes it is.

**Comment by mschauer** [comment]
I am currently working with Levy driven SDEs, so `Gamma` and `t` and other self decomposable distributions are also in the back of my mind.

**Comment by ChrisRackauckas** [comment]
Regular Poisson jump processes are another planned. You might want to see https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/261

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/SciCompDSL.jl/pull/26
