### ISSUE TITLE
Simplification macros

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SciCompDSL.jl#25]
```julia
@DV x y z
@IV t
@Parameter σ,ρ,β
D = Derivative(t)
de = @diffeq begin
  D*x = σ*(y-x)
  D*y = x*(ρ-z)-y
  D*z = x*y - β*z
end
```

would be very nice. Basically it just assumes you want the name to match the variable name, which is very reasonable and probably recommended. It can also allow for having the value placed after the names, so like:

```julia
@DV x 2.0 y 3.0 z 4.0
```

**Comment by AleMorales** [comment]
If you use `=` for the value assignment you could have expressions to calculate complex default values and easily mix variables with and without default values like
```
@DV x = 2.0 y = exp(3) z
```
and the macro will still capture three variables (x,y,z) and nicely associate each value (or expression that evaluates to value) to each name.

**Comment by ChrisRackauckas** [comment]
That looks great! I think it would be nice to also parse the following:

```julia
@DV begin 
  x = 2.0
  y = exp(3)
  z
end
```
