### ISSUE TITLE
Add functions of parameters

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/SciCompDSL.jl#27]
A useful extension of SciCompDSL would be to specify functions of parameters to allow coding of within and across equation restrictions. For instance, the first order ODE with speed of adjustment a

Dy = abX + ac - ay written as Dy = F1X + F2 -ay with F1 = ab and F2 = ac ; a, b, c are parameters

**Comment by ChrisRackauckas** [comment]
This is already done with function registration and intermediate variables.
