### ISSUE TITLE
Remove distinction between dependent and independent variables

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/SciCompDSL.jl#31]
Is the distinction between dependent and independent variables really necessary? Doesn't that arise at the moment of specifying the DE? I will want to use this stuff in other contexts (not DEs) where that distinction doesn't make sense.

**Comment by ChrisRackauckas** [comment]
>I will want to use this stuff in other contexts (not DEs) where that distinction doesn't make sense.

Then just use `Variable`? That's what that's made for. IV and DV is created for auto-detection of context to allow the `DiffEqSystem` construction to auto-detect variables, variable order, auto-build the initial condition vector, etc. But for other contexts you can just use non-contextualized `Variable` or create other contexts by using different `Variable` subtypes. For example, a nonlinear system would just use `Variable` and `Parameter`. 

BTW, what kind of application are you looking to do this for?

**Comment by dpsanders** [comment]
Ah OK, thanks.

I think I can adopt it wholesale to replace a lot of 
https://github.com/dpsanders/IntervalConstraintProgramming.jl

**Comment by ChrisRackauckas** [comment]
The README now clearly shows that you don't need to use tagged variables in the nonlinear system construction section:

https://github.com/JuliaDiffEq/SciCompDSL.jl#example-nonlinear-system
