### ISSUE TITLE
Using a binary operator with lower precedence instead of `==`

### ISSUE THREAD

**Issue by AleMorales** [JuliaDiffEq/SciCompDSL.jl#41]
The precedence level of `==` is only 6 (according to `Base.operator_precedence(:(==))`, whereas the arrows (like → or ⟺) have a precedence level of 5. This is an issue with the ReactionDSL (alemorales/reactiondsl.jl#4) but I think it could appear with other DSL that use SciComp as target for code lowering.

Since the `==` is actually being used as a form of assignment (to variables, derivatives, etc), I think it would make more sense to use one of the operators from the assignment-like operators [`prec-assignment`](https://github.com/JuliaLang/julia/blob/c200b4cdb9620b6df369ae3c735cf3af30b6a47f/src/julia-parser.scm).

A potential candidate could be `~` which is not used as binary operator in Base. There is precedent for this symbol, as this was the choice in probabilistic programming languages like JAGS, Stan or Turing to assign distributions to stochastic variables.

**Comment by ChrisRackauckas** [comment]
I think I am in support of this. Trying to use `==` and other boolean operators is causing problems in generic codes (`inv`) and so we should probably leave them alone instead of making them an operation. This was already showing its ugly head via `isequal` being very different than `==`.

**Comment by ChrisRackauckas** [comment]
The possible operators are shown here:

https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L10-L11

I think it's a choice between `~` and `:=`, and I particularly like `:=`.

**Comment by AleMorales** [comment]
I thought `:=` does not work outside of macros (julialang/julia#23014). Indeed, I keep getting "invalid identifier name".  I liked the idea the SciCompDSL does not require a macro to generate the AST.

**Comment by ChrisRackauckas** [comment]
Oh dang, it looks like `~` and `$=` are the only decent choices, and `$=` reminds me too much of Perl. `~` it is. Let's do this.

**Comment by dlfivefifty** [comment]
Overrides like overriding `==` to mean something else is why Java forbid operator overloading completely...

I like `~`

**Comment by tshort** [comment]
I like `~`, too. Note that if `~` is not behind a macro, there's some chance that another package (or Base) will define methods for this. That would lead to ambiguity messages. It probably won't bite us, but it's hard to say for sure.

**Comment by ChrisRackauckas** [comment]
>I like ~, too. Note that if ~ is not behind a macro, there's some chance that another package (or Base) will define methods for this. That would lead to ambiguity messages. It probably won't bite us, but it's hard to say for sure.

No, there's 6 methods in Base for bit twiddling, so we can extend instead of define since we are using our own types.

**Comment by tshort** [comment]
But, if you have `0 ~ myvar = 3`, we own the right side but not the left. So, if someone defines `~(x::SomeType, y::Any)`, it'll have an ambiguity with our definition.

**Comment by ChrisRackauckas** [comment]
We should only have to define it between our types and at most `Number` with one of our types (that's how we have the operation overloading done right now, combinations of `Expression` and `Number`), so that should stop any ambiguity with an `Any` definition. Also, I'm not sure we can make `=` work well with what we are doing, or if we even want to do that.

**Comment by ChrisRackauckas** [comment]
I changed it all to `~` and added an ambiguity test to make sure that `~(x::SomeType, y::Number)` isn't throwing errors.

**Comment by simonbyrne** [comment]
Just chiming in here to note that probabilistic modelling DSLs (e.g. WinBUGS, Stan) tend to use `~` to denote random quantities, e.g.
```
X ~ Normal(0,1)
```

**Comment by dlfivefifty** [comment]
I just came across ≣ (`\Equiv`) which is another option if we were happy with unicode.

**Comment by ChrisRackauckas** [comment]
I don't want any user facing unicode.
