### ISSUE TITLE
Optimal Control API

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaDiffEq/SciCompDSL.jl#42]
As per [this issue](https://github.com/JuliaMPC/NLOptControl.jl/issues/5), I am going to list the things needed for an optimal control problem. Really there are three things, states, controls and parameters. 

# State Variables 
This is equal to the number of differential equations, typically ``x1``, ....``xn`` were ``n``  is the number of states

# Control Variables 
Typically ``u1``, ....``um`` were ``m``  is the number of controls

# Parameters 
These might be ``p1``.....``pq`` where ``q`` is the number of parameters.

There are also a few more things that I have listed [here](https://juliampc.github.io/MPCDocs.jl/latest/tutorials/Brachistochrone/main.html#Basics-1), but I am not sure if I need different API for things like the initial state etc.

@ChrisRackauckas is this what you were asking for?

**Comment by ChrisRackauckas** [comment]
Yup thanks for the writeup. So it looks like a two variable + parameter pairing is what's needed. `DependentVariable` for states and `Variable` for the control variables would work, and we can just add the aliasing between the names `DependentVariable` and `StateVariable` along with an alias of `ControlVariable` and `Variable`.

**Comment by ChrisRackauckas** [comment]
Actually we'd want to keep `Variable` separate for intermediate calculations, so we should add `ControlVariable` and that would make it easy to automatically detect that it's an optimal control problem.

**Comment by huckl3b3rry87** [comment]
Yeah, that sounds good. Also, ultimately it is important for me to convert whatever the user gives into expressions so that I can use JuMP, is that out of scope for this package?

**Comment by ChrisRackauckas** [comment]
That's in scope.

**Comment by huckl3b3rry87** [comment]
@ChrisRackauckas great!

**Comment by huckl3b3rry87** [comment]
Also, it would be good to extend your ``@Var`` macro to define new names for the state and control variables such as:
```
@StateVar X Y PSI
```
and 
```
@ControlVar U AX
```
I did this before using a [function](https://github.com/JuliaMPC/NLOptControl.jl/blob/master/src/utils.jl#L189)

**Comment by ChrisRackauckas** [comment]
Is `@DVar` fine? It would make interopability easier with DiffEq to not add another name if it's unnecessary.

**Comment by huckl3b3rry87** [comment]
There should be a difference between state and control variables. Are you suggesting using ``@Dvar`` for the states and controls?

**Comment by ChrisRackauckas** [comment]
No, just states.

**Comment by huckl3b3rry87** [comment]
yeah, that is fine! What does ``@Dvar`` stand for? It sounds like design varaible

**Comment by ChrisRackauckas** [comment]
Dependent variable.

**Comment by huckl3b3rry87** [comment]
ah, that works!

**Comment by huckl3b3rry87** [comment]
Could ``@Var`` be used for the controls?

**Comment by ChrisRackauckas** [comment]
We'll want that for intermediate calculations.
