### ISSUE TITLE
Variable sizes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SciCompDSL.jl#5]
Each variable should have a sizing that determines if it's an array or not, but also what kind of array it is.

**Comment by AleMorales** [comment]
Why fix the kind of array at that point? It would be better to generate a valid diffeq problem that stays as generic as the "manually built" ones. Maybe just specify mutability so that the system cand figure whether to generate an in-place and out-of-place version?

**Comment by ChrisRackauckas** [comment]
By "kind of array" I meant dimension.

**Comment by AleMorales** [comment]
So what is sizing then?

**Comment by ChrisRackauckas** [comment]
The length in each dimension. I think I just said it poorly.
