### ISSUE TITLE
Handle literals

### ISSUE THREAD

**Issue by AleMorales** [JuliaDiffEq/SciCompDSL.jl#7]
Arithmetic involving literals (e.g. `2*v1` where `v1` is a `Variable`) does not work. I cannot imagine a convenient DSL without them. But we cannot extend the registered functions to deal with `Real`, so I am not sure at the moment how to handle this (using `Constant` is possible, but all the nice syntax goes away...).

**Comment by ChrisRackauckas** [comment]
Yeah, there must be some way to do automatic promotions here.

**Comment by AleMorales** [comment]
Is there a way to promote only one of the operands? That is, `promote_rule` will promote both arguments, but we only want to promote the literal to a `Constant`. For example, doing this `Base.promote_rule(::Type{<:Expression}, ::Type{<:Integer}) = Constant` does not work :(

**Comment by ChrisRackauckas** [comment]
We can just have the registration macro automatically make `(Number,Expression)` dispatches add `Constant` on the numbers etc.

**Comment by ChrisRackauckas** [comment]
Also, this can be handled in the `@diffeq` macro and things like that if it has to be.

**Comment by AleMorales** [comment]
> We can just have the registration macro automatically make (Number,Expression) dispatches add Constant on the numbers etc.

Yes, I think that would be the best approach for now. And this could handle all the permutations of argument types.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/SciCompDSL.jl/pull/12
